apiVersion: v1
kind: Namespace
metadata:
  name: managed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-managed
  namespace: managed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-managed
  template:
    metadata:
      labels:
        app: nginx-managed
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80

